User.create(username: "Vicki", email: "vicki@hamm.com", password: "mypassword")
User.create(username: "Mags", email: "mags@hamm.com", password: "apassword")
User.create(username: "Diana", email: "diana@hamm.com", password: "thepassword")
User.create(username: "Eric", email: "eric@hamm.com", password: "thispassword")

Book.create(title: "Psychology in the 21st Century", author: "Della Fitz")
Book.create(title: "The Female Perspective" , author: "Audre Lorde")
Book.create(title: "Bunnies", author: "Beatrix Potter")
Book.create(title: "Forensic Files", author: "Georgia Hardstark")
Book.create(title: "Your Brain and Music", author: "A Musicologist")

UserBook.create(comment: "Comment by Vicki - This Book is Rad", user_id: 1, book_id: 2)
UserBook.create(comment: "Comment by Eric - My Favorite Murder Mystery", user_id: 4, book_id: 4)
UserBook.create(comment: "Comment by Mags - This is such a musical book", user_id: 2, book_id: 5)
UserBook.create(comment: "Comment by Diana - This Book is Rad", user_id: 3, book_id: 1)
UserBook.create(comment: "Comment by Vicki - I love bunnies", user_id: 1, book_id: 3)