User.create(username: "Vicki", email: "vicki@hamm.com", password: "mypassword")
User.create(username: "Mags", email: "mags@hamm.com", password: "apassword")
User.create(username: "Diana", email: "diana@hamm.com", password: "thepassword")
User.create(username: "Eric", email: "eric@hamm.com", password: "thispassword")

Book.create(title: "Psychology in the 21st Century", author: "Della Fitz")
Book.create(title: "The Female Perspective" , author: "Audre Lorde")
Book.create(title: "Bunnies", author: "Beatrix Potter")
Book.create(title: "Forensic Files", author: "Georgia Hardstark")
Book.create(title: "Your Brain and Music", author: "A Musicologist")